//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public Cat()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage="*")]
        public string Name { get; set; }
        public string Keywords { get; set; }
        public string Descriptin { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> Position { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
