//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
namespace forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
         [Required(ErrorMessage = "*")]
        [AllowHtml]
        public string Content { get; set; }
        [Required (ErrorMessage="*")]
        public string Title { get; set; }
        public int TopcID { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsShow { get; set; }
        public Nullable<short> Position { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
    }
}
