//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cat
{
    public Cat()
    {
        this.Topics = new HashSet<Topic>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public string Keywords { get; set; }
    public string Descriptin { get; set; }
    public Nullable<bool> IsShow { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<short> Position { get; set; }
    public int UserId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }

    public virtual User User { get; set; }
    public virtual ICollection<Topic> Topics { get; set; }
}

public partial class Comment
{
    public int ID { get; set; }
    public string Content { get; set; }
    public string Title { get; set; }
    public int TopcID { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date { get; set; }
    public bool IsShow { get; set; }
    public Nullable<short> Position { get; set; }

    public virtual Topic Topic { get; set; }
    public virtual User User { get; set; }
}

public partial class Role
{
    public Role()
    {
        this.Users = new HashSet<User>();
    }

    public short ID { get; set; }
    public string RolrName { get; set; }

    public virtual ICollection<User> Users { get; set; }
}

public partial class Topic
{
    public Topic()
    {
        this.Comments = new HashSet<Comment>();
    }

    public int ID { get; set; }
    public string Title { get; set; }
    public string Descriptin { get; set; }
    public bool IsActive { get; set; }
    public bool IsShow { get; set; }
    public Nullable<short> Position { get; set; }
    public int CatId { get; set; }
    public Nullable<System.DateTime> LastUpdate { get; set; }
    public string Keywords { get; set; }
    public int UserID { get; set; }

    public virtual Cat Cat { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual User User { get; set; }
}

public partial class User
{
    public User()
    {
        this.Cats = new HashSet<Cat>();
        this.Comments = new HashSet<Comment>();
        this.Topics = new HashSet<Topic>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public string LastName { get; set; }
    public string Password { get; set; }
    public string UserName { get; set; }
    public string Email { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> RegistDate { get; set; }
    public Nullable<System.DateTime> LastActivity { get; set; }
    public string Image { get; set; }
    public Nullable<short> RoleID { get; set; }

    public virtual ICollection<Cat> Cats { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual Role Role { get; set; }
    public virtual ICollection<Topic> Topics { get; set; }
}
