//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage="*")]
        public string Title { get; set; }
        public string Descriptin { get; set; }
        public bool IsActive { get; set; }
        public bool IsShow { get; set; }
        public Nullable<short> Position { get; set; }
         [Required(ErrorMessage = "*")]
        public int CatId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Keywords { get; set; }
        public int UserID { get; set; }
         
        public virtual Cat Cat { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
    }
}
